_target_: datamodule.pubtabnet.PubTabNet
root_dir: /table/table_structure/dataset/mini_pubtabnet
label_type: ${dataset.label_type}
split: train
json_html: mini_pubtabnet_examples.jsonl
transform: ${dataset.augmentation}
cell_limit: 150
otsl_mode: ${trainer.trainer.otsl_mode}