
_target_: datamodule.pubtabnet.PubTabNet
root_dir: /table/table_structure/dataset/pubtabnet
label_type: ${dataset.label_type}
split: train
json_html: PubTabNet_2.0.0_ori_processed.jsonl
transform: ${dataset.augmentation}
cell_limit: ${dataset.cell_limit}