
_target_: datamodule.pubtabnet.PubTabNet
root_dir: /table/table_structure/dataset/fintabnet_processed
label_type: ${dataset.label_type}
split: train
json_html: annotation.jsonl
transform: ${dataset.augmentation}
cell_limit: 150