
_target_: datamodule.pubtabnet.PubTabNet
root_dir: /table/table_structure/dataset/generator/gen_2025_03_21_formula_1000
label_type: ${dataset.label_type}
split: train
json_html: annotations.jsonl
transform: ${dataset.augmentation}
cell_limit: 150
otsl_mode: ${trainer.trainer.otsl_mode}