
_target_: datamodule.pubtabnet.PubTabNet
root_dir: /table/table_structure/dataset/pubtabnet_50K_train0.9_val0.1_clean
label_type: ${dataset.label_type}
split: train
json_html: annotations.jsonl
transform: ${dataset.augmentation}
cell_limit: 150
otsl_mode: ${trainer.trainer.otsl_mode}