_target_: datamodule.pubtabnet.PubTabNet
root_dir: /table/table_structure/dataset/IX_dataset/MVP30_target_case2_250617_1_300
label_type: ${dataset.label_type}
split: train
json_html: annotations.jsonl
transform: ${dataset.augmentation}
cell_limit: 150
otsl_mode: ${trainer.trainer.otsl_mode}