_target_: datamodule.synthtabnet.Synthtabnet
root_dir: /table/table_structure/dataset/SynthTabNet/pubtabnet_147.5K_train0.8_val0.2_clean
label_type: ${dataset.label_type}
split: train
json_html: annotations.jsonl
transform: ${dataset.augmentation}
cell_limit: ${dataset.cell_limit}
otsl_mode: ${trainer.trainer.otsl_mode}