
_target_: datamodule.pubtabnet.PubTabNet
root_dir: /table/table_structure/dataset/generator/gen_2025_03_25_image_1000
label_type: ${dataset.label_type}
split: train
json_html: IX_generator.jsonl
transform: ${dataset.augmentation}
cell_limit: 150